### ISSUE TITLE
关于下载

### ISSUE THREAD

**Issue by xiaoniangaoh** [handy-git/AfDianPay#1]
作者能不能打包一下，自从bbs寄了以后国内的好的插件都找不到了呜呜呜
![A959A7B612035ABFFB13EF2EC4BE03A8](https://github.com/handy-git/AfDianPay/assets/112637370/f03ce36b-3a2b-40c3-927b-75ef15776ad5)

**Comment by handy-git** [comment]
> 作者能不能打包一下，自从bbs寄了以后国内的好的插件都找不到了呜呜呜 ![A959A7B612035ABFFB13EF2EC4BE03A8](https://private-user-images.githubusercontent.com/112637370/316526564-f03ce36b-3a2b-40c3-927b-75ef15776ad5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MTgyMTQsIm5iZiI6MTcxMTQxNzkxNCwicGF0aCI6Ii8xMTI2MzczNzAvMzE2NTI2NTY0LWYwM2NlMzZiLTNhMmItNDBjMy05MjdiLTc1ZWYxNTc3NmFkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQwMTUxNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODE0N2YzZjQ2OGM3OGYzMTlkN2M2MmNkYjA1MGRiYjRhMzYzMzNkNzBlM2FkMWMwOTkzYzQ1MzRiNjZmZTdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yYsE4Dp8LTuBUd4fAizUfKz6Df-UmArCNwTqGgvHhSM)

https://ricedoc.handyplus.cn/ 在这里找插件
